Relax tolerance for eightcells snapshot (a lot)
Going from numpy 2.3.0 to numpy 2.3.2 we observe the difference

FAILED tests/everest/test_eightcells_simulation.py::test_eightcells_snapshot - AssertionError: Values do not match for best_controls
     batch_id  realization  simulation_id  well_rate.OP1.1  well_rate.WI1.1
  0         1            0              0        50.179885       268.831775
  1         1            1              1        50.179885       268.831775
  2         1            2              2        50.179885       268.831775

     batch_id  realization  simulation_id  well_rate.OP1.1  well_rate.WI1.1
  0         1            0              0        50.223395        268.30478
  1         1            1              1        50.223395        268.30478
  2         1            2              2        50.223395        268.30478

which is not too interestint to capture. Keep the tolerance low at least
for some time until upgrade has stabilized.