Fix misfit plot attribute error if missing observations
This commit fixes the issue where the misfit plotter would fail with `AttributeError: 'NoneType' object has no attribute 'T'` if observations for an ensemble was missing.
Now, it will plot a message `No observations available`